{
	"version": 1530868840,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/backg.png",
		"images/table.png",
		"images/story.png",
		"images/selector-sheet0.png",
		"images/selector-sheet1.png",
		"images/selector-sheet2.png",
		"images/cross-sheet0.png",
		"images/done-sheet0.png",
		"images/trait.png",
		"images/page-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/fondtek-sheet0.png",
		"images/fondtek-sheet1.png",
		"images/sprite2-sheet0.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}